id: P005646
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W19606
  title: མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་དགོངས་དོན་རབ་གསལ
  author: ''
  volumes:
    9c731c3911c24fa7a9b47ffb79d0d01f:
      image_group_id: I0447
      title: ''
      volume_number: 1
      total_pages: 235
      base_file: v001.txt
